import Head from 'next/head'
import Categories from '../components/Categories'
import PostCard from '../components/PostCard'
import PostWeidget from '../components/PostWeidget'

export default function Home() {
  return (
    <div className="Container mx-auto px-0 mb-0 w-full">
      <Head>
        <title>7Empire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon_io/favicon-32x32.png" />
      </Head>
      <div className='body grid grid-rows-4 grid-cols-5 gap-x-30'>
        <div className='post-container row-start-1 row-span-4	col-span-3'>
          <div>
            <PostCard/>
          </div>
        </div>
        <div className='aside row-start-1 row-span-4 col-span-2 p-50'>
          <div className='recent-post'>
            <PostWeidget/>
          </div>
          <div className='categories'>
            <Categories/>
          </div>
        </div>
      </div>
    </div>
  )
}
