import Head from 'next/head'
import Image from 'next/image'
import logo_footer from '../public/logo.jpg'
import {FaFacebook, FaTwitterSquare, FaInstagram, FaLinkedin, FaYoutube}  from 'react-icons/fa'

export default function Home() {
  return (
    <div className="Container mx-auto px-0 mb-0 w-full">
      <Head>
        <title>7Empire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon_io/favicon-32x32.png" />
      </Head>
      <div className='header flex flex-row items-center justify-between bg-black text-white'>
        <Image src={logo_footer} alt='logo' className='logo md:w-50' />
        <div className='navBar' id='myNavbar'>
          <ul className='navList flex flex-row gap-20 font-black'>
              <li className='hover:text-red-600 cursor-pointer'>Home</li>
              <li className='hover:text-red-600 cursor-pointer'>Categories</li>
              <li className='hover:text-red-600 cursor-pointer'>Tutos</li>
              <li className='hover:text-red-600 cursor-pointer'>About</li>
              <li className='hover:text-red-600 cursor-pointer'>Contact</li>
          </ul>
        </div>
      </div>


      <div className='body grid grid-rows-4 grid-cols-5 gap-x-30'>
        <div className='post-container row-start-1 row-span-4	col-span-3'>
          <div>post</div>
        </div>
        <div className='aside row-start-1 row-span-4 col-span-2 p-50'>
          <div className='recent-post'>recents post</div>
          <div className='categories'>categories</div>
        </div>
      </div>


      <div className="footer flex flex-col bg-black text-white w-full absolute bottom-0 pt-5">
          <div className='footer-social flex flex-row justify-center items-center'>
            <Image src={logo_footer} alt='logo footer' className='logo_footer'/>
            <div className='social-icons flex flex-row justify-center items-center'>
              <FaFacebook className='icone hover:text-red-600 cursor-pointer'/>
              <FaTwitterSquare className='icone hover:text-red-600 cursor-pointer'/>
              <FaInstagram className='icone hover:text-red-600 cursor-pointer'/>
              <FaLinkedin className='icone hover:text-red-600 cursor-pointer'/>
              <FaYoutube className='icone hover:text-red-600 cursor-pointer'/>
            </div>
          </div>
          <ul className='ulFooter flex flex-row gap-20 justify-center p-30 items-center font-bolt'>
              <li className='hover:text-red-600 cursor-pointer'>Home</li>
              <li className='hover:text-red-600 cursor-pointer'>Blog</li>
              <li className='hover:text-red-600 cursor-pointer'>About</li>
              <li className='hover:text-red-600 cursor-pointer'>Contact</li>
              <li className='hover:text-red-600 cursor-pointer'>Terms and Conditions</li>
              <li className='hover:text-red-600 cursor-pointer'>Cookie policy</li>
              <li className='hover:text-red-600 cursor-pointer'>Distribution</li>
              <li className='hover:text-red-600 cursor-pointer'>Advertising</li>
              <li className='hover:text-red-600 cursor-pointer'>Jobs</li>
          </ul>
      </div>
    </div>
  )
}
